version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: irkpo_sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrong@Passw0rd
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - irkpo_network
    restart: unless-stopped

  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: irkpo_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=sa
      - DB_PASSWORD=YourStrong@Passw0rd
      - DB_ENCRYPT=${DB_ENCRYPT}
      - DB_TRUST_SERVER_CERTIFICATE=${DB_TRUST_SERVER_CERTIFICATE}
    depends_on:
      - sqlserver
    networks:
      - irkpo_network
    restart: unless-stopped

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: irkpo_nginx
    ports:
      - "8080:80"  # Changed from 80:80 to avoid port conflict
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - irkpo_network
    restart: unless-stopped

  # Vite Development Server (for hot reload)
  vite:
    build:
      context: .
      dockerfile: Dockerfile
      target: node
    container_name: irkpo_vite
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    networks:
      - irkpo_network
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  irkpo_network:
    driver: bridge
